defmodule Intellispark.Repo.Migrations.AddSurveyTemplateVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:survey_template_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:survey_templates) do
      modify(
        :current_version_id,
        references(:survey_template_versions,
          column: :id,
          name: "survey_templates_current_version_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create index(:survey_templates, [:school_id, :current_version_id])

    alter table(:survey_template_versions) do
      add(:schema, :map, null: false)
      add(:published_at, :utc_datetime_usec, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "survey_template_versions_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :survey_template_id,
        references(:survey_templates,
          column: :id,
          name: "survey_template_versions_survey_template_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:survey_template_versions_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:survey_template_id, :uuid, null: false)

      add(
        :version_source_id,
        references(:survey_template_versions,
          column: :id,
          name: "survey_template_versions_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(
      constraint(
        :survey_template_versions_versions,
        "survey_template_versions_versions_version_source_id_fkey"
      )
    )

    drop(table(:survey_template_versions_versions))

    drop(constraint(:survey_template_versions, "survey_template_versions_school_id_fkey"))

    drop(
      constraint(:survey_template_versions, "survey_template_versions_survey_template_id_fkey")
    )

    alter table(:survey_template_versions) do
      remove(:survey_template_id)
      remove(:school_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:published_at)
      remove(:schema)
    end

    drop_if_exists(index(:survey_templates, [:school_id, :current_version_id]))

    drop(constraint(:survey_templates, "survey_templates_current_version_id_fkey"))

    alter table(:survey_templates) do
      modify(:current_version_id, :uuid)
    end

    drop(table(:survey_template_versions))
  end
end
