defmodule Intellispark.Repo.Migrations.AddExternalPersonsAndPolymorphicKeyConnection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:key_connections) do
      add(:connected_external_person_id, :uuid)
    end

    drop_if_exists(
      unique_index(:key_connections, [:school_id, :student_id, :connected_user_id],
        name: "key_connections_unique_per_student_user_index"
      )
    )

    alter table(:key_connections) do
      modify(:connected_user_id, :uuid, null: true)
    end

    create unique_index(:key_connections, [:school_id, :student_id, :connected_user_id],
             name: "key_connections_unique_per_student_user_index",
             where: "(connected_user_id IS NOT NULL)"
           )

    create unique_index(
             :key_connections,
             [:school_id, :student_id, :connected_external_person_id],
             name: "key_connections_unique_per_student_external_person_index",
             where: "(connected_external_person_id IS NOT NULL)"
           )

    create table(:external_persons, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:key_connections) do
      modify(
        :connected_external_person_id,
        references(:external_persons,
          column: :id,
          name: "key_connections_connected_external_person_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:external_persons) do
      add(:first_name, :text, null: false)
      add(:last_name, :text, null: false)
      add(:relationship_kind, :text, null: false)
      add(:email, :text)
      add(:phone, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "external_persons_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :added_by_id,
        references(:users,
          column: :id,
          name: "external_persons_added_by_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:key_connections_versions) do
      modify(:connected_user_id, :uuid, null: true)
      add(:connected_external_person_id, :uuid)
    end

    create table(:external_persons_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)

      add(
        :version_source_id,
        references(:external_persons,
          column: :id,
          name: "external_persons_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(
      constraint(:external_persons_versions, "external_persons_versions_version_source_id_fkey")
    )

    drop(table(:external_persons_versions))

    alter table(:key_connections_versions) do
      remove(:connected_external_person_id)
      modify(:connected_user_id, :uuid, null: false)
    end

    drop(constraint(:external_persons, "external_persons_school_id_fkey"))

    drop(constraint(:external_persons, "external_persons_added_by_id_fkey"))

    alter table(:external_persons) do
      remove(:added_by_id)
      remove(:school_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:phone)
      remove(:email)
      remove(:relationship_kind)
      remove(:last_name)
      remove(:first_name)
    end

    drop(constraint(:key_connections, "key_connections_connected_external_person_id_fkey"))

    alter table(:key_connections) do
      modify(:connected_external_person_id, :uuid)
    end

    drop(table(:external_persons))

    drop_if_exists(
      unique_index(:key_connections, [:school_id, :student_id, :connected_external_person_id],
        name: "key_connections_unique_per_student_external_person_index"
      )
    )

    drop_if_exists(
      unique_index(:key_connections, [:school_id, :student_id, :connected_user_id],
        name: "key_connections_unique_per_student_user_index"
      )
    )

    alter table(:key_connections) do
      modify(:connected_user_id, :uuid, null: false)
    end

    create unique_index(:key_connections, [:school_id, :student_id, :connected_user_id],
             name: "key_connections_unique_per_student_user_index"
           )

    alter table(:key_connections) do
      remove(:connected_external_person_id)
    end
  end
end
