defmodule Intellispark.Repo.Migrations.DropDemoSessionArchivedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:demo_sessions) do
      remove(:archived_at)
    end
  end

  def down do
    alter table(:demo_sessions) do
      add(:archived_at, :utc_datetime_usec)
    end
  end
end
