defmodule Intellispark.Repo.Migrations.AddFlagAssignments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:flag_assignments_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:flag_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:flag_assignments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:flag_assignments_versions) do
      modify(
        :version_source_id,
        references(:flag_assignments,
          column: :id,
          name: "flag_assignments_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:flag_assignments) do
      add(:assigned_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:cleared_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "flag_assignments_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :flag_id,
        references(:flags,
          column: :id,
          name: "flag_assignments_flag_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "flag_assignments_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :assigned_by_id,
        references(:users,
          column: :id,
          name: "flag_assignments_assigned_by_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:flag_assignments, [:school_id, :flag_id, :user_id],
             name: "flag_assignments_unique_active_assignment_index"
           )
  end

  def down do
    drop(constraint(:flag_assignments, "flag_assignments_school_id_fkey"))

    drop(constraint(:flag_assignments, "flag_assignments_flag_id_fkey"))

    drop(constraint(:flag_assignments, "flag_assignments_user_id_fkey"))

    drop(constraint(:flag_assignments, "flag_assignments_assigned_by_id_fkey"))

    drop_if_exists(
      unique_index(:flag_assignments, [:school_id, :flag_id, :user_id],
        name: "flag_assignments_unique_active_assignment_index"
      )
    )

    alter table(:flag_assignments) do
      remove(:archived_at)
      remove(:assigned_by_id)
      remove(:user_id)
      remove(:flag_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:cleared_at)
      remove(:assigned_at)
    end

    drop(
      constraint(:flag_assignments_versions, "flag_assignments_versions_version_source_id_fkey")
    )

    alter table(:flag_assignments_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:flag_assignments))

    drop(table(:flag_assignments_versions))
  end
end
