defmodule Intellispark.Repo.Migrations.AddSurveyQuestions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:survey_questions_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:survey_template_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:survey_questions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:survey_questions_versions) do
      modify(
        :version_source_id,
        references(:survey_questions,
          column: :id,
          name: "survey_questions_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:survey_questions) do
      add(:prompt, :text, null: false)
      add(:help_text, :text)
      add(:position, :bigint, null: false, default: 0)
      add(:required?, :boolean, null: false, default: false)
      add(:question_type, :text, null: false, default: "short_text")
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "survey_questions_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :survey_template_id,
        references(:survey_templates,
          column: :id,
          name: "survey_questions_survey_template_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:survey_questions, "survey_questions_school_id_fkey"))

    drop(constraint(:survey_questions, "survey_questions_survey_template_id_fkey"))

    alter table(:survey_questions) do
      remove(:survey_template_id)
      remove(:school_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:metadata)
      remove(:question_type)
      remove(:required?)
      remove(:position)
      remove(:help_text)
      remove(:prompt)
    end

    drop(
      constraint(:survey_questions_versions, "survey_questions_versions_version_source_id_fkey")
    )

    alter table(:survey_questions_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:survey_questions))

    drop(table(:survey_questions_versions))
  end
end
