defmodule Intellispark.Repo.Migrations.AddEmailPreferencesToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add(:email_preferences, :map, default: %{})
    end
  end

  def down do
    alter table(:users) do
      remove(:email_preferences)
    end
  end
end
