defmodule Intellispark.Repo.Migrations.CreateAccountsResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:users_versions) do
      modify(
        :version_source_id,
        references(:users,
          column: :id,
          name: "users_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:users) do
      add(:email, :citext, null: false)
      add(:hashed_password, :text, null: false)
      add(:first_name, :text)
      add(:last_name, :text)
      add(:confirmed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:district_id, :uuid)
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:user_school_memberships_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:user_school_memberships, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:user_school_memberships_versions) do
      modify(
        :version_source_id,
        references(:user_school_memberships,
          column: :id,
          name: "user_school_memberships_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:user_school_memberships) do
      add(:role, :text, null: false)
      add(:source, :text, null: false, default: "manual")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "user_school_memberships_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:school_id, :uuid, null: false)
    end

    create unique_index(:user_school_memberships, [:user_id, :school_id],
             name: "user_school_memberships_unique_user_school_index"
           )

    create table(:tokens, primary_key: false) do
      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:extra_data, :map)
      add(:purpose, :text, null: false)
      add(:expires_at, :utc_datetime, null: false)
      add(:subject, :text, null: false)
      add(:jti, :text, null: false, primary_key: true)
    end

    create table(:schools_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:schools, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:user_school_memberships) do
      modify(
        :school_id,
        references(:schools,
          column: :id,
          name: "user_school_memberships_school_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:schools_versions) do
      modify(
        :version_source_id,
        references(:schools,
          column: :id,
          name: "schools_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:schools) do
      add(:name, :text, null: false)
      add(:slug, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
      add(:district_id, :uuid, null: false)
    end

    create unique_index(:schools, [:district_id, :slug],
             name: "schools_unique_slug_per_district_index"
           )

    create table(:school_terms_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:school_terms, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:school_terms_versions) do
      modify(
        :version_source_id,
        references(:school_terms,
          column: :id,
          name: "school_terms_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:school_terms) do
      add(:name, :text, null: false)
      add(:starts_on, :date, null: false)
      add(:ends_on, :date, null: false)
      add(:is_current?, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "school_terms_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create table(:districts_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:districts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:users) do
      modify(
        :district_id,
        references(:districts,
          column: :id,
          name: "users_district_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:schools) do
      modify(
        :district_id,
        references(:districts,
          column: :id,
          name: "schools_district_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:districts_versions) do
      modify(
        :version_source_id,
        references(:districts,
          column: :id,
          name: "districts_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:districts) do
      add(:name, :text, null: false)
      add(:slug, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:districts, [:slug], name: "districts_unique_slug_index")
  end

  def down do
    drop_if_exists(unique_index(:districts, [:slug], name: "districts_unique_slug_index"))

    alter table(:districts) do
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:slug)
      remove(:name)
    end

    drop(constraint(:districts_versions, "districts_versions_version_source_id_fkey"))

    alter table(:districts_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(constraint(:schools, "schools_district_id_fkey"))

    alter table(:schools) do
      modify(:district_id, :uuid)
    end

    drop(constraint(:users, "users_district_id_fkey"))

    alter table(:users) do
      modify(:district_id, :uuid)
    end

    drop(table(:districts))

    drop(table(:districts_versions))

    drop(constraint(:school_terms, "school_terms_school_id_fkey"))

    alter table(:school_terms) do
      remove(:school_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:is_current?)
      remove(:ends_on)
      remove(:starts_on)
      remove(:name)
    end

    drop(constraint(:school_terms_versions, "school_terms_versions_version_source_id_fkey"))

    alter table(:school_terms_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:school_terms))

    drop(table(:school_terms_versions))

    drop_if_exists(
      unique_index(:schools, [:district_id, :slug],
        name: "schools_unique_slug_per_district_index"
      )
    )

    alter table(:schools) do
      remove(:district_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:slug)
      remove(:name)
    end

    drop(constraint(:schools_versions, "schools_versions_version_source_id_fkey"))

    alter table(:schools_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(constraint(:user_school_memberships, "user_school_memberships_school_id_fkey"))

    alter table(:user_school_memberships) do
      modify(:school_id, :uuid)
    end

    drop(table(:schools))

    drop(table(:schools_versions))

    drop(table(:tokens))

    drop(constraint(:user_school_memberships, "user_school_memberships_user_id_fkey"))

    drop_if_exists(
      unique_index(:user_school_memberships, [:user_id, :school_id],
        name: "user_school_memberships_unique_user_school_index"
      )
    )

    alter table(:user_school_memberships) do
      remove(:school_id)
      remove(:user_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:source)
      remove(:role)
    end

    drop(
      constraint(
        :user_school_memberships_versions,
        "user_school_memberships_versions_version_source_id_fkey"
      )
    )

    alter table(:user_school_memberships_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:user_school_memberships))

    drop(table(:user_school_memberships_versions))

    drop_if_exists(unique_index(:users, [:email], name: "users_unique_email_index"))

    alter table(:users) do
      remove(:district_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:confirmed_at)
      remove(:last_name)
      remove(:first_name)
      remove(:hashed_password)
      remove(:email)
    end

    drop(constraint(:users_versions, "users_versions_version_source_id_fkey"))

    alter table(:users_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:users))

    drop(table(:users_versions))
  end
end
