defmodule Intellispark.Repo.Migrations.Phase185BillingDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:school_subscriptions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tier, :text, null: false, default: "starter")
      add(:status, :text, null: false, default: "active")
      add(:seats, :bigint, default: 0)

      add(:started_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:renews_at, :utc_datetime_usec)
      add(:stripe_subscription_id, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "school_subscriptions_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:school_subscriptions, [:school_id],
             name: "school_subscriptions_unique_school_index"
           )

    create table(:school_subscriptions_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)

      add(
        :version_source_id,
        references(:school_subscriptions,
          column: :id,
          name: "school_subscriptions_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:school_onboarding_states, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:current_step, :text, null: false, default: "school_profile")
      add(:school_profile_completed_at, :utc_datetime_usec)
      add(:invite_coadmins_completed_at, :utc_datetime_usec)
      add(:starter_tags_completed_at, :utc_datetime_usec)
      add(:sis_provider_completed_at, :utc_datetime_usec)
      add(:pick_tier_completed_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "school_onboarding_states_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:school_onboarding_states, [:school_id],
             name: "school_onboarding_states_unique_school_index"
           )

    create table(:school_onboarding_states_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)

      add(
        :version_source_id,
        references(:school_onboarding_states,
          column: :id,
          name: "school_onboarding_states_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(
      constraint(
        :school_onboarding_states_versions,
        "school_onboarding_states_versions_version_source_id_fkey"
      )
    )

    drop(table(:school_onboarding_states_versions))

    drop(constraint(:school_onboarding_states, "school_onboarding_states_school_id_fkey"))

    drop_if_exists(
      unique_index(:school_onboarding_states, [:school_id],
        name: "school_onboarding_states_unique_school_index"
      )
    )

    drop(table(:school_onboarding_states))

    drop(
      constraint(
        :school_subscriptions_versions,
        "school_subscriptions_versions_version_source_id_fkey"
      )
    )

    drop(table(:school_subscriptions_versions))

    drop(constraint(:school_subscriptions, "school_subscriptions_school_id_fkey"))

    drop_if_exists(
      unique_index(:school_subscriptions, [:school_id],
        name: "school_subscriptions_unique_school_index"
      )
    )

    drop(table(:school_subscriptions))
  end
end
