defmodule Intellispark.Repo.Migrations.AddSurveyTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:survey_templates, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:published?, :boolean, null: false, default: false)
      add(:duration_minutes, :bigint, default: 5)
      add(:current_version_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "survey_templates_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:survey_templates, [:school_id, :name],
             name: "survey_templates_unique_name_per_school_index"
           )

    create table(:survey_templates_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)

      add(
        :version_source_id,
        references(:survey_templates,
          column: :id,
          name: "survey_templates_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(
      constraint(:survey_templates_versions, "survey_templates_versions_version_source_id_fkey")
    )

    drop(table(:survey_templates_versions))

    drop(constraint(:survey_templates, "survey_templates_school_id_fkey"))

    drop_if_exists(
      unique_index(:survey_templates, [:school_id, :name],
        name: "survey_templates_unique_name_per_school_index"
      )
    )

    drop(table(:survey_templates))
  end
end
