defmodule Intellispark.Repo.Migrations.AddSurveyResponses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:survey_responses, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:answer_text, :text)
      add(:answer_values, {:array, :text}, default: [])

      add(:answered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:survey_assignment_id, :uuid, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "survey_responses_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :question_id,
        references(:survey_questions,
          column: :id,
          name: "survey_responses_question_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:survey_responses, [:school_id, :survey_assignment_id, :question_id],
             name: "survey_responses_unique_response_per_question_index"
           )

    create table(:survey_responses_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:survey_assignment_id, :uuid, null: false)
      add(:school_id, :uuid, null: false)
      add(:question_id, :uuid, null: false)

      add(
        :version_source_id,
        references(:survey_responses,
          column: :id,
          name: "survey_responses_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(
      constraint(:survey_responses_versions, "survey_responses_versions_version_source_id_fkey")
    )

    drop(table(:survey_responses_versions))

    drop(constraint(:survey_responses, "survey_responses_school_id_fkey"))

    drop(constraint(:survey_responses, "survey_responses_question_id_fkey"))

    drop_if_exists(
      unique_index(:survey_responses, [:school_id, :survey_assignment_id, :question_id],
        name: "survey_responses_unique_response_per_question_index"
      )
    )

    drop(table(:survey_responses))
  end
end
