defmodule Intellispark.Repo.Migrations.AddSchoolInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:school_invitations_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:school_invitations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:school_invitations_versions) do
      modify(
        :version_source_id,
        references(:school_invitations,
          column: :id,
          name: "school_invitations_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:school_invitations) do
      add(:email, :citext, null: false)
      add(:role, :text, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:expires_at, :utc_datetime_usec, null: false)
      add(:accepted_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "school_invitations_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :inviter_id,
        references(:users,
          column: :id,
          name: "school_invitations_inviter_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:school_invitations, [:email, :school_id],
             name: "school_invitations_one_pending_per_email_school_index",
             where: "(status = 'pending')"
           )
  end

  def down do
    drop(constraint(:school_invitations, "school_invitations_school_id_fkey"))

    drop(constraint(:school_invitations, "school_invitations_inviter_id_fkey"))

    drop_if_exists(
      unique_index(:school_invitations, [:email, :school_id],
        name: "school_invitations_one_pending_per_email_school_index"
      )
    )

    alter table(:school_invitations) do
      remove(:archived_at)
      remove(:inviter_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:accepted_at)
      remove(:expires_at)
      remove(:status)
      remove(:role)
      remove(:email)
    end

    drop(
      constraint(
        :school_invitations_versions,
        "school_invitations_versions_version_source_id_fkey"
      )
    )

    alter table(:school_invitations_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:school_invitations))

    drop(table(:school_invitations_versions))
  end
end
