defmodule Intellispark.Repo.Migrations.XelloCompletedLessons do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:xello_profiles) do
      add(:completed_lessons, {:array, :text}, default: [])
    end
  end

  def down do
    alter table(:xello_profiles) do
      remove(:completed_lessons)
    end
  end
end
