defmodule Intellispark.Repo.Migrations.AddResentAtToHighFives do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:high_fives) do
      add(:resent_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:high_fives) do
      remove(:resent_at)
    end
  end
end
