defmodule Intellispark.Repo.Migrations.AddHighFiveViews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:high_five_views, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:user_agent, :text)
      add(:ip_hash, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "high_five_views_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :high_five_id,
        references(:high_fives,
          column: :id,
          name: "high_five_views_high_five_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:high_five_views, "high_five_views_school_id_fkey"))

    drop(constraint(:high_five_views, "high_five_views_high_five_id_fkey"))

    drop(table(:high_five_views))
  end
end
