defmodule Intellispark.Repo.Migrations.InterventionLibrary do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:supports) do
      add(:intervention_library_item_id, :uuid)
    end

    create table(:intervention_library_items_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:intervention_library_items, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:supports) do
      modify(
        :intervention_library_item_id,
        references(:intervention_library_items,
          column: :id,
          name: "supports_intervention_library_item_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:intervention_library_items_versions) do
      modify(
        :version_source_id,
        references(:intervention_library_items,
          column: :id,
          name: "intervention_library_items_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:intervention_library_items) do
      add(:title, :text, null: false)
      add(:description, :text)
      add(:mtss_tier, :text, null: false)
      add(:default_duration_days, :bigint, default: 30)
      add(:active?, :boolean, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "intervention_library_items_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end
  end

  def down do
    drop(constraint(:intervention_library_items, "intervention_library_items_school_id_fkey"))

    alter table(:intervention_library_items) do
      remove(:archived_at)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:active?)
      remove(:default_duration_days)
      remove(:mtss_tier)
      remove(:description)
      remove(:title)
    end

    drop(
      constraint(
        :intervention_library_items_versions,
        "intervention_library_items_versions_version_source_id_fkey"
      )
    )

    alter table(:intervention_library_items_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(constraint(:supports, "supports_intervention_library_item_id_fkey"))

    alter table(:supports) do
      modify(:intervention_library_item_id, :uuid)
    end

    drop(table(:intervention_library_items))

    drop(table(:intervention_library_items_versions))

    alter table(:supports) do
      remove(:intervention_library_item_id)
    end
  end
end
