defmodule Intellispark.Repo.Migrations.AddTeamMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:team_memberships_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:role, :text, null: false)
      add(:source, :text, null: false, default: "manual")
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)
      add(:user_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:team_memberships, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:team_memberships_versions) do
      modify(
        :version_source_id,
        references(:team_memberships,
          column: :id,
          name: "team_memberships_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:team_memberships) do
      add(:role, :text, null: false)
      add(:source, :text, null: false, default: "manual")

      add(:added_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:permissions_override, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "team_memberships_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "team_memberships_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "team_memberships_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :added_by_id,
        references(:users,
          column: :id,
          name: "team_memberships_added_by_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:team_memberships, [:school_id, :student_id, :user_id, :role],
             name: "team_memberships_unique_per_student_user_role_index"
           )
  end

  def down do
    drop(constraint(:team_memberships, "team_memberships_school_id_fkey"))

    drop(constraint(:team_memberships, "team_memberships_student_id_fkey"))

    drop(constraint(:team_memberships, "team_memberships_user_id_fkey"))

    drop(constraint(:team_memberships, "team_memberships_added_by_id_fkey"))

    drop_if_exists(
      unique_index(:team_memberships, [:school_id, :student_id, :user_id, :role],
        name: "team_memberships_unique_per_student_user_role_index"
      )
    )

    alter table(:team_memberships) do
      remove(:added_by_id)
      remove(:user_id)
      remove(:student_id)
      remove(:school_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:permissions_override)
      remove(:added_at)
      remove(:source)
      remove(:role)
    end

    drop(
      constraint(:team_memberships_versions, "team_memberships_versions_version_source_id_fkey")
    )

    alter table(:team_memberships_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:team_memberships))

    drop(table(:team_memberships_versions))
  end
end
