defmodule Intellispark.Repo.Migrations.AddActions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:actions_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:actions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:actions_versions) do
      modify(
        :version_source_id,
        references(:actions,
          column: :id,
          name: "actions_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:actions) do
      add(:description, :text, null: false)
      add(:due_on, :date)
      add(:completed_at, :utc_datetime_usec)
      add(:cancellation_reason, :text)
      add(:status, :text, null: false, default: "pending")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "actions_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "actions_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :assignee_id,
        references(:users,
          column: :id,
          name: "actions_assignee_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :opened_by_id,
        references(:users,
          column: :id,
          name: "actions_opened_by_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :completed_by_id,
        references(:users,
          column: :id,
          name: "actions_completed_by_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:actions, "actions_school_id_fkey"))

    drop(constraint(:actions, "actions_student_id_fkey"))

    drop(constraint(:actions, "actions_assignee_id_fkey"))

    drop(constraint(:actions, "actions_opened_by_id_fkey"))

    drop(constraint(:actions, "actions_completed_by_id_fkey"))

    alter table(:actions) do
      remove(:completed_by_id)
      remove(:opened_by_id)
      remove(:assignee_id)
      remove(:student_id)
      remove(:school_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:status)
      remove(:cancellation_reason)
      remove(:completed_at)
      remove(:due_on)
      remove(:description)
    end

    drop(constraint(:actions_versions, "actions_versions_version_source_id_fkey"))

    alter table(:actions_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:actions))

    drop(table(:actions_versions))
  end
end
