defmodule Intellispark.Repo.Migrations.AddTagsAndStudentTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:tags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:tags_versions) do
      modify(
        :version_source_id,
        references(:tags,
          column: :id,
          name: "tags_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:tags) do
      add(:name, :text, null: false)
      add(:color, :text, null: false, default: "#2b4366")
      add(:description, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "tags_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:tags, [:school_id, :name], name: "tags_unique_name_per_school_index")

    create table(:student_tags_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:student_tags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:student_tags_versions) do
      modify(
        :version_source_id,
        references(:student_tags,
          column: :id,
          name: "student_tags_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:student_tags) do
      add(:applied_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "student_tags_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "student_tags_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :tag_id,
        references(:tags,
          column: :id,
          name: "student_tags_tag_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :applied_by_id,
        references(:users,
          column: :id,
          name: "student_tags_applied_by_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:student_tags, [:school_id, :student_id, :tag_id],
             name: "student_tags_unique_student_tag_index"
           )
  end

  def down do
    drop(constraint(:student_tags, "student_tags_school_id_fkey"))

    drop(constraint(:student_tags, "student_tags_student_id_fkey"))

    drop(constraint(:student_tags, "student_tags_tag_id_fkey"))

    drop(constraint(:student_tags, "student_tags_applied_by_id_fkey"))

    drop_if_exists(
      unique_index(:student_tags, [:school_id, :student_id, :tag_id],
        name: "student_tags_unique_student_tag_index"
      )
    )

    alter table(:student_tags) do
      remove(:archived_at)
      remove(:applied_by_id)
      remove(:tag_id)
      remove(:student_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:applied_at)
    end

    drop(constraint(:student_tags_versions, "student_tags_versions_version_source_id_fkey"))

    alter table(:student_tags_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:student_tags))

    drop(table(:student_tags_versions))

    drop(constraint(:tags, "tags_school_id_fkey"))

    drop_if_exists(
      unique_index(:tags, [:school_id, :name], name: "tags_unique_name_per_school_index")
    )

    alter table(:tags) do
      remove(:archived_at)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:description)
      remove(:color)
      remove(:name)
    end

    drop(constraint(:tags_versions, "tags_versions_version_source_id_fkey"))

    alter table(:tags_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:tags))

    drop(table(:tags_versions))
  end
end
