defmodule Intellispark.Repo.Migrations.AddStudentEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:students) do
      add(:email, :text)
    end
  end

  def down do
    alter table(:students) do
      remove(:email)
    end
  end
end
