defmodule Intellispark.Repo.Migrations.AddFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:flags_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:status, :text, null: false, default: "draft")
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:flags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:flags_versions) do
      modify(
        :version_source_id,
        references(:flags,
          column: :id,
          name: "flags_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:flags) do
      add(:description, :text, null: false)
      add(:short_description, :text)
      add(:sensitive?, :boolean, null: false, default: false)
      add(:resolution_note, :text)
      add(:followup_at, :date)
      add(:auto_close_at, :utc_datetime_usec)
      add(:status, :text, null: false, default: "draft")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "flags_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "flags_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :flag_type_id,
        references(:flag_types,
          column: :id,
          name: "flags_flag_type_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :opened_by_id,
        references(:users,
          column: :id,
          name: "flags_opened_by_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :closed_by_id,
        references(:users,
          column: :id,
          name: "flags_closed_by_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:archived_at, :utc_datetime_usec)
    end
  end

  def down do
    drop(constraint(:flags, "flags_school_id_fkey"))

    drop(constraint(:flags, "flags_student_id_fkey"))

    drop(constraint(:flags, "flags_flag_type_id_fkey"))

    drop(constraint(:flags, "flags_opened_by_id_fkey"))

    drop(constraint(:flags, "flags_closed_by_id_fkey"))

    alter table(:flags) do
      remove(:archived_at)
      remove(:closed_by_id)
      remove(:opened_by_id)
      remove(:flag_type_id)
      remove(:student_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:status)
      remove(:auto_close_at)
      remove(:followup_at)
      remove(:resolution_note)
      remove(:sensitive?)
      remove(:short_description)
      remove(:description)
    end

    drop(constraint(:flags_versions, "flags_versions_version_source_id_fkey"))

    alter table(:flags_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:flags))

    drop(table(:flags_versions))
  end
end
