defmodule Intellispark.Repo.Migrations.AddStrengths do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:strengths_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:strengths, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:strengths_versions) do
      modify(
        :version_source_id,
        references(:strengths,
          column: :id,
          name: "strengths_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:strengths) do
      add(:description, :text, null: false)
      add(:display_order, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "strengths_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "strengths_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :added_by_id,
        references(:users,
          column: :id,
          name: "strengths_added_by_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:strengths, "strengths_school_id_fkey"))

    drop(constraint(:strengths, "strengths_student_id_fkey"))

    drop(constraint(:strengths, "strengths_added_by_id_fkey"))

    alter table(:strengths) do
      remove(:added_by_id)
      remove(:student_id)
      remove(:school_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:display_order)
      remove(:description)
    end

    drop(constraint(:strengths_versions, "strengths_versions_version_source_id_fkey"))

    alter table(:strengths_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:strengths))

    drop(table(:strengths_versions))
  end
end
