defmodule Intellispark.Repo.Migrations.AddKeyConnections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:key_connections, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:note, :text)
      add(:source, :text, null: false, default: "added_manually")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "key_connections_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "key_connections_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :connected_user_id,
        references(:users,
          column: :id,
          name: "key_connections_connected_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :added_by_id,
        references(:users,
          column: :id,
          name: "key_connections_added_by_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:key_connections, [:school_id, :student_id, :connected_user_id],
             name: "key_connections_unique_per_student_user_index"
           )

    create table(:key_connections_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)
      add(:connected_user_id, :uuid, null: false)

      add(
        :version_source_id,
        references(:key_connections,
          column: :id,
          name: "key_connections_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(constraint(:key_connections_versions, "key_connections_versions_version_source_id_fkey"))

    drop(table(:key_connections_versions))

    drop(constraint(:key_connections, "key_connections_school_id_fkey"))

    drop(constraint(:key_connections, "key_connections_student_id_fkey"))

    drop(constraint(:key_connections, "key_connections_connected_user_id_fkey"))

    drop(constraint(:key_connections, "key_connections_added_by_id_fkey"))

    drop_if_exists(
      unique_index(:key_connections, [:school_id, :student_id, :connected_user_id],
        name: "key_connections_unique_per_student_user_index"
      )
    )

    drop(table(:key_connections))
  end
end
