defmodule Intellispark.Repo.Migrations.AddHighFiveViewSchoolId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:high_five_views_versions) do
      add(:school_id, :uuid, null: false)
    end
  end

  def down do
    alter table(:high_five_views_versions) do
      remove(:school_id)
    end
  end
end
