defmodule Intellispark.Repo.Migrations.AddStatuses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:students) do
      add(:current_status_id, :uuid)
    end

    create table(:student_statuses_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:student_statuses, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:student_statuses_versions) do
      modify(
        :version_source_id,
        references(:student_statuses,
          column: :id,
          name: "student_statuses_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:student_statuses) do
      add(:set_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:cleared_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "student_statuses_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "student_statuses_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:status_id, :uuid, null: false)
      add(:set_by_id, :uuid, null: false)
      add(:archived_at, :utc_datetime_usec)
    end

    create table(:statuses_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:statuses, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:students) do
      modify(
        :current_status_id,
        references(:statuses,
          column: :id,
          name: "students_current_status_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:student_statuses) do
      modify(
        :status_id,
        references(:statuses,
          column: :id,
          name: "student_statuses_status_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :set_by_id,
        references(:users,
          column: :id,
          name: "student_statuses_set_by_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:statuses_versions) do
      modify(
        :version_source_id,
        references(:statuses,
          column: :id,
          name: "statuses_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:statuses) do
      add(:name, :text, null: false)
      add(:color, :text, null: false, default: "#4b4b4d")
      add(:position, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "statuses_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:statuses, [:school_id, :name],
             name: "statuses_unique_name_per_school_index"
           )
  end

  def down do
    drop(constraint(:statuses, "statuses_school_id_fkey"))

    drop_if_exists(
      unique_index(:statuses, [:school_id, :name], name: "statuses_unique_name_per_school_index")
    )

    alter table(:statuses) do
      remove(:archived_at)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:position)
      remove(:color)
      remove(:name)
    end

    drop(constraint(:statuses_versions, "statuses_versions_version_source_id_fkey"))

    alter table(:statuses_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(constraint(:student_statuses, "student_statuses_status_id_fkey"))

    drop(constraint(:student_statuses, "student_statuses_set_by_id_fkey"))

    alter table(:student_statuses) do
      modify(:set_by_id, :uuid)
      modify(:status_id, :uuid)
    end

    drop(constraint(:students, "students_current_status_id_fkey"))

    alter table(:students) do
      modify(:current_status_id, :uuid)
    end

    drop(table(:statuses))

    drop(table(:statuses_versions))

    drop(constraint(:student_statuses, "student_statuses_school_id_fkey"))

    drop(constraint(:student_statuses, "student_statuses_student_id_fkey"))

    alter table(:student_statuses) do
      remove(:archived_at)
      remove(:set_by_id)
      remove(:status_id)
      remove(:student_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:cleared_at)
      remove(:set_at)
    end

    drop(
      constraint(:student_statuses_versions, "student_statuses_versions_version_source_id_fkey")
    )

    alter table(:student_statuses_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:student_statuses))

    drop(table(:student_statuses_versions))

    alter table(:students) do
      remove(:current_status_id)
    end
  end
end
