defmodule Intellispark.Repo.Migrations.AddStudentDemographics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:students) do
      add(:phone, :text)
      add(:gender, :text)
      add(:ethnicity_race, :text)
    end
  end

  def down do
    alter table(:students) do
      remove(:ethnicity_race)
      remove(:gender)
      remove(:phone)
    end
  end
end
