defmodule Intellispark.Repo.Migrations.AddSupports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:supports, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:description, :text)
      add(:starts_at, :date)
      add(:ends_at, :date)
      add(:decline_reason, :text)
      add(:status, :text, null: false, default: "offered")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "supports_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "supports_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :offered_by_id,
        references(:users,
          column: :id,
          name: "supports_offered_by_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :provider_staff_id,
        references(:users,
          column: :id,
          name: "supports_provider_staff_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:supports_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:status, :text, null: false, default: "offered")
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)

      add(
        :version_source_id,
        references(:supports,
          column: :id,
          name: "supports_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(constraint(:supports_versions, "supports_versions_version_source_id_fkey"))

    drop(table(:supports_versions))

    drop(constraint(:supports, "supports_school_id_fkey"))

    drop(constraint(:supports, "supports_student_id_fkey"))

    drop(constraint(:supports, "supports_offered_by_id_fkey"))

    drop(constraint(:supports, "supports_provider_staff_id_fkey"))

    drop(table(:supports))
  end
end
