defmodule Intellispark.Repo.Migrations.ResiliencyResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:resiliency_assessments_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:resiliency_assessments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:resiliency_assessments_versions) do
      modify(
        :version_source_id,
        references(:resiliency_assessments,
          column: :id,
          name: "resiliency_assessments_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:resiliency_assessments) do
      add(:grade_band, :text, null: false)
      add(:version, :text, null: false)
      add(:state, :text, null: false, default: "assigned")
      add(:token, :text, null: false)

      add(:assigned_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:submitted_at, :utc_datetime_usec)
      add(:expires_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "resiliency_assessments_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "resiliency_assessments_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :assigned_by_id,
        references(:users,
          column: :id,
          name: "resiliency_assessments_assigned_by_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:resiliency_assessments, [:school_id, :token],
             name: "resiliency_assessments_unique_token_index"
           )

    create table(:resiliency_responses_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:question_id, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:assessment_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:resiliency_skill_scores_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:skill, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:resiliency_responses, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:resiliency_responses_versions) do
      modify(
        :version_source_id,
        references(:resiliency_responses,
          column: :id,
          name: "resiliency_responses_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:resiliency_responses) do
      add(:question_id, :text, null: false)
      add(:value, :bigint, null: false)

      add(:answered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "resiliency_responses_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :assessment_id,
        references(:resiliency_assessments,
          column: :id,
          name: "resiliency_responses_assessment_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:resiliency_responses, [:school_id, :assessment_id, :question_id],
             name: "resiliency_responses_unique_per_assessment_question_index"
           )

    create table(:resiliency_skill_scores, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:resiliency_skill_scores_versions) do
      modify(
        :version_source_id,
        references(:resiliency_skill_scores,
          column: :id,
          name: "resiliency_skill_scores_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:resiliency_skill_scores) do
      add(:skill, :text, null: false)
      add(:score_value, :float, null: false)
      add(:level, :text, null: false)
      add(:answered_count, :bigint, null: false, default: 0)

      add(:last_computed_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "resiliency_skill_scores_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "resiliency_skill_scores_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :assessment_id,
        references(:resiliency_assessments,
          column: :id,
          name: "resiliency_skill_scores_assessment_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:resiliency_skill_scores, [:school_id, :student_id, :skill],
             name: "resiliency_skill_scores_unique_per_student_skill_index"
           )
  end

  def down do
    drop(constraint(:resiliency_skill_scores, "resiliency_skill_scores_school_id_fkey"))

    drop(constraint(:resiliency_skill_scores, "resiliency_skill_scores_student_id_fkey"))

    drop(constraint(:resiliency_skill_scores, "resiliency_skill_scores_assessment_id_fkey"))

    drop_if_exists(
      unique_index(:resiliency_skill_scores, [:school_id, :student_id, :skill],
        name: "resiliency_skill_scores_unique_per_student_skill_index"
      )
    )

    alter table(:resiliency_skill_scores) do
      remove(:archived_at)
      remove(:assessment_id)
      remove(:student_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:last_computed_at)
      remove(:answered_count)
      remove(:level)
      remove(:score_value)
      remove(:skill)
    end

    drop(
      constraint(
        :resiliency_skill_scores_versions,
        "resiliency_skill_scores_versions_version_source_id_fkey"
      )
    )

    alter table(:resiliency_skill_scores_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:resiliency_skill_scores))

    drop(constraint(:resiliency_responses, "resiliency_responses_school_id_fkey"))

    drop(constraint(:resiliency_responses, "resiliency_responses_assessment_id_fkey"))

    drop_if_exists(
      unique_index(:resiliency_responses, [:school_id, :assessment_id, :question_id],
        name: "resiliency_responses_unique_per_assessment_question_index"
      )
    )

    alter table(:resiliency_responses) do
      remove(:archived_at)
      remove(:assessment_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:answered_at)
      remove(:value)
      remove(:question_id)
    end

    drop(
      constraint(
        :resiliency_responses_versions,
        "resiliency_responses_versions_version_source_id_fkey"
      )
    )

    alter table(:resiliency_responses_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:resiliency_responses))

    drop(table(:resiliency_skill_scores_versions))

    drop(table(:resiliency_responses_versions))

    drop(constraint(:resiliency_assessments, "resiliency_assessments_school_id_fkey"))

    drop(constraint(:resiliency_assessments, "resiliency_assessments_student_id_fkey"))

    drop(constraint(:resiliency_assessments, "resiliency_assessments_assigned_by_id_fkey"))

    drop_if_exists(
      unique_index(:resiliency_assessments, [:school_id, :token],
        name: "resiliency_assessments_unique_token_index"
      )
    )

    alter table(:resiliency_assessments) do
      remove(:archived_at)
      remove(:assigned_by_id)
      remove(:student_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:expires_at)
      remove(:submitted_at)
      remove(:assigned_at)
      remove(:token)
      remove(:state)
      remove(:version)
      remove(:grade_band)
    end

    drop(
      constraint(
        :resiliency_assessments_versions,
        "resiliency_assessments_versions_version_source_id_fkey"
      )
    )

    alter table(:resiliency_assessments_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:resiliency_assessments))

    drop(table(:resiliency_assessments_versions))
  end
end
