defmodule Intellispark.Repo.Migrations.AddSurveyAssignments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:survey_assignments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:survey_responses) do
      modify(
        :survey_assignment_id,
        references(:survey_assignments,
          column: :id,
          name: "survey_responses_survey_assignment_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create index(:survey_responses, [:school_id, :survey_assignment_id])

    alter table(:survey_assignments) do
      add(:state, :text, null: false, default: "assigned")
      add(:token, :text, null: false)

      add(:assigned_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:first_opened_at, :utc_datetime_usec)
      add(:submitted_at, :utc_datetime_usec)
      add(:expires_at, :utc_datetime_usec)
      add(:last_reminded_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "survey_assignments_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "survey_assignments_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :assigned_by_id,
        references(:users,
          column: :id,
          name: "survey_assignments_assigned_by_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :survey_template_id,
        references(:survey_templates,
          column: :id,
          name: "survey_assignments_survey_template_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :survey_template_version_id,
        references(:survey_template_versions,
          column: :id,
          name: "survey_assignments_survey_template_version_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:survey_assignments, [:school_id, :token],
             name: "survey_assignments_unique_token_index"
           )

    create table(:survey_assignments_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:state, :text, null: false, default: "assigned")
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)

      add(
        :version_source_id,
        references(:survey_assignments,
          column: :id,
          name: "survey_assignments_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(
      constraint(
        :survey_assignments_versions,
        "survey_assignments_versions_version_source_id_fkey"
      )
    )

    drop(table(:survey_assignments_versions))

    drop(constraint(:survey_assignments, "survey_assignments_school_id_fkey"))

    drop(constraint(:survey_assignments, "survey_assignments_student_id_fkey"))

    drop(constraint(:survey_assignments, "survey_assignments_assigned_by_id_fkey"))

    drop(constraint(:survey_assignments, "survey_assignments_survey_template_id_fkey"))

    drop(constraint(:survey_assignments, "survey_assignments_survey_template_version_id_fkey"))

    drop_if_exists(
      unique_index(:survey_assignments, [:school_id, :token],
        name: "survey_assignments_unique_token_index"
      )
    )

    alter table(:survey_assignments) do
      remove(:survey_template_version_id)
      remove(:survey_template_id)
      remove(:assigned_by_id)
      remove(:student_id)
      remove(:school_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:last_reminded_at)
      remove(:expires_at)
      remove(:submitted_at)
      remove(:first_opened_at)
      remove(:assigned_at)
      remove(:token)
      remove(:state)
    end

    drop_if_exists(index(:survey_responses, [:school_id, :survey_assignment_id]))

    drop(constraint(:survey_responses, "survey_responses_survey_assignment_id_fkey"))

    alter table(:survey_responses) do
      modify(:survey_assignment_id, :uuid)
    end

    drop(table(:survey_assignments))
  end
end
