defmodule Intellispark.Repo.Migrations.Phase11IntegrationsCore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:integration_sync_runs_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:provider_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:embed_tokens, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:token, :text, null: false)
      add(:audience, :text, null: false, default: "xello")
      add(:expires_at, :utc_datetime_usec, null: false)
      add(:revoked_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "embed_tokens_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "embed_tokens_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :created_by_id,
        references(:users,
          column: :id,
          name: "embed_tokens_created_by_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:embed_tokens, [:school_id, :student_id, :audience],
             name: "embed_tokens_unique_per_student_audience_index"
           )

    create unique_index(:embed_tokens, [:school_id, :token],
             name: "embed_tokens_unique_token_index"
           )

    create table(:integration_sync_runs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:integration_sync_runs_versions) do
      modify(
        :version_source_id,
        references(:integration_sync_runs,
          column: :id,
          name: "integration_sync_runs_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:integration_sync_runs) do
      add(:status, :text, null: false, default: "pending")
      add(:started_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)
      add(:records_processed, :bigint, default: 0)
      add(:records_created, :bigint, default: 0)
      add(:records_updated, :bigint, default: 0)
      add(:records_failed, :bigint, default: 0)
      add(:trigger_source, :text, default: "scheduled")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "integration_sync_runs_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:provider_id, :uuid, null: false)
      add(:archived_at, :utc_datetime_usec)
    end

    create table(:xello_profiles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:personality_style, :map, default: %{})
      add(:learning_style, :map, default: %{})
      add(:education_goals, :text)
      add(:favorite_career_clusters, {:array, :text}, default: [])
      add(:skills, {:array, :text}, default: [])
      add(:interests, {:array, :text}, default: [])
      add(:birthplace, :text)
      add(:live_in, :text)
      add(:family_roots, :text)
      add(:suggested_clusters, {:array, :text}, default: [])

      add(:last_synced_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "xello_profiles_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "xello_profiles_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:xello_profiles, [:school_id, :student_id],
             name: "xello_profiles_unique_per_student_index"
           )

    create table(:integration_sync_errors_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:sync_run_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:integration_providers_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:integration_sync_errors, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:integration_sync_errors_versions) do
      modify(
        :version_source_id,
        references(:integration_sync_errors,
          column: :id,
          name: "integration_sync_errors_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:integration_sync_errors) do
      add(:raw_payload, :map, null: false)
      add(:error_message, :text, null: false)
      add(:error_kind, :text, default: "validation")
      add(:resolved?, :boolean, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "integration_sync_errors_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :sync_run_id,
        references(:integration_sync_runs,
          column: :id,
          name: "integration_sync_errors_sync_run_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:xello_profiles_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)

      add(
        :version_source_id,
        references(:xello_profiles,
          column: :id,
          name: "xello_profiles_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:embed_tokens_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)

      add(
        :version_source_id,
        references(:embed_tokens,
          column: :id,
          name: "embed_tokens_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:integration_providers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:integration_sync_runs) do
      modify(
        :provider_id,
        references(:integration_providers,
          column: :id,
          name: "integration_sync_runs_provider_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:integration_providers_versions) do
      modify(
        :version_source_id,
        references(:integration_providers,
          column: :id,
          name: "integration_providers_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:integration_providers) do
      add(:provider_type, :text, null: false)
      add(:name, :text, null: false)
      add(:credentials, :binary, null: false)
      add(:active?, :boolean, default: true)
      add(:last_synced_at, :utc_datetime_usec)
      add(:last_success_at, :utc_datetime_usec)
      add(:last_failure_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "integration_providers_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:integration_providers, [:school_id, :provider_type],
             name: "integration_providers_unique_type_per_school_index"
           )
  end

  def down do
    drop(constraint(:integration_providers, "integration_providers_school_id_fkey"))

    drop_if_exists(
      unique_index(:integration_providers, [:school_id, :provider_type],
        name: "integration_providers_unique_type_per_school_index"
      )
    )

    alter table(:integration_providers) do
      remove(:archived_at)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:last_failure_at)
      remove(:last_success_at)
      remove(:last_synced_at)
      remove(:active?)
      remove(:credentials)
      remove(:name)
      remove(:provider_type)
    end

    drop(
      constraint(
        :integration_providers_versions,
        "integration_providers_versions_version_source_id_fkey"
      )
    )

    alter table(:integration_providers_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(constraint(:integration_sync_runs, "integration_sync_runs_provider_id_fkey"))

    alter table(:integration_sync_runs) do
      modify(:provider_id, :uuid)
    end

    drop(table(:integration_providers))

    drop(constraint(:embed_tokens_versions, "embed_tokens_versions_version_source_id_fkey"))

    drop(table(:embed_tokens_versions))

    drop(constraint(:xello_profiles_versions, "xello_profiles_versions_version_source_id_fkey"))

    drop(table(:xello_profiles_versions))

    drop(constraint(:integration_sync_errors, "integration_sync_errors_school_id_fkey"))

    drop(constraint(:integration_sync_errors, "integration_sync_errors_sync_run_id_fkey"))

    alter table(:integration_sync_errors) do
      remove(:archived_at)
      remove(:sync_run_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:resolved?)
      remove(:error_kind)
      remove(:error_message)
      remove(:raw_payload)
    end

    drop(
      constraint(
        :integration_sync_errors_versions,
        "integration_sync_errors_versions_version_source_id_fkey"
      )
    )

    alter table(:integration_sync_errors_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:integration_sync_errors))

    drop(table(:integration_providers_versions))

    drop(table(:integration_sync_errors_versions))

    drop(constraint(:xello_profiles, "xello_profiles_school_id_fkey"))

    drop(constraint(:xello_profiles, "xello_profiles_student_id_fkey"))

    drop_if_exists(
      unique_index(:xello_profiles, [:school_id, :student_id],
        name: "xello_profiles_unique_per_student_index"
      )
    )

    drop(table(:xello_profiles))

    drop(constraint(:integration_sync_runs, "integration_sync_runs_school_id_fkey"))

    alter table(:integration_sync_runs) do
      remove(:archived_at)
      remove(:provider_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:trigger_source)
      remove(:records_failed)
      remove(:records_updated)
      remove(:records_created)
      remove(:records_processed)
      remove(:completed_at)
      remove(:started_at)
      remove(:status)
    end

    drop(
      constraint(
        :integration_sync_runs_versions,
        "integration_sync_runs_versions_version_source_id_fkey"
      )
    )

    alter table(:integration_sync_runs_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:integration_sync_runs))

    drop(constraint(:embed_tokens, "embed_tokens_school_id_fkey"))

    drop(constraint(:embed_tokens, "embed_tokens_student_id_fkey"))

    drop(constraint(:embed_tokens, "embed_tokens_created_by_id_fkey"))

    drop_if_exists(
      unique_index(:embed_tokens, [:school_id, :token], name: "embed_tokens_unique_token_index")
    )

    drop_if_exists(
      unique_index(:embed_tokens, [:school_id, :student_id, :audience],
        name: "embed_tokens_unique_per_student_audience_index"
      )
    )

    drop(table(:embed_tokens))

    drop(table(:integration_sync_runs_versions))
  end
end
