defmodule Intellispark.Repo.Migrations.AddFlagTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:flag_types_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:flag_types, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:flag_types_versions) do
      modify(
        :version_source_id,
        references(:flag_types,
          column: :id,
          name: "flag_types_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:flag_types) do
      add(:name, :text, null: false)
      add(:color, :text, null: false, default: "#A1452E")
      add(:default_sensitive?, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "flag_types_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:flag_types, [:school_id, :name],
             name: "flag_types_unique_name_per_school_index"
           )
  end

  def down do
    drop(constraint(:flag_types, "flag_types_school_id_fkey"))

    drop_if_exists(
      unique_index(:flag_types, [:school_id, :name],
        name: "flag_types_unique_name_per_school_index"
      )
    )

    alter table(:flag_types) do
      remove(:archived_at)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:default_sensitive?)
      remove(:color)
      remove(:name)
    end

    drop(constraint(:flag_types_versions, "flag_types_versions_version_source_id_fkey"))

    alter table(:flag_types_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:flag_types))

    drop(table(:flag_types_versions))
  end
end
