defmodule Intellispark.Repo.Migrations.AddStudents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:students_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:students, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:students_versions) do
      modify(
        :version_source_id,
        references(:students,
          column: :id,
          name: "students_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:students) do
      add(:first_name, :text, null: false)
      add(:last_name, :text, null: false)
      add(:preferred_name, :text)
      add(:date_of_birth, :date)
      add(:grade_level, :bigint)
      add(:enrollment_status, :text, null: false, default: "active")
      add(:external_id, :text)
      add(:photo_url, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "students_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:students, [:school_id, :external_id],
             name: "students_unique_external_id_per_school_index",
             where: "(external_id IS NOT NULL)"
           )
  end

  def down do
    drop(constraint(:students, "students_school_id_fkey"))

    drop_if_exists(
      unique_index(:students, [:school_id, :external_id],
        name: "students_unique_external_id_per_school_index"
      )
    )

    alter table(:students) do
      remove(:archived_at)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:photo_url)
      remove(:external_id)
      remove(:enrollment_status)
      remove(:grade_level)
      remove(:date_of_birth)
      remove(:preferred_name)
      remove(:last_name)
      remove(:first_name)
    end

    drop(constraint(:students_versions, "students_versions_version_source_id_fkey"))

    alter table(:students_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:students))

    drop(table(:students_versions))
  end
end
