defmodule Intellispark.Repo.Migrations.AddCustomLists do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:custom_lists_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:custom_lists, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:custom_lists_versions) do
      modify(
        :version_source_id,
        references(:custom_lists,
          column: :id,
          name: "custom_lists_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:custom_lists) do
      add(:name, :text, null: false)
      add(:description, :text)
      add(:filters, :map, null: false)
      add(:shared?, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "custom_lists_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :owner_id,
        references(:users,
          column: :id,
          name: "custom_lists_owner_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end
  end

  def down do
    drop(constraint(:custom_lists, "custom_lists_school_id_fkey"))

    drop(constraint(:custom_lists, "custom_lists_owner_id_fkey"))

    alter table(:custom_lists) do
      remove(:archived_at)
      remove(:owner_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:shared?)
      remove(:filters)
      remove(:description)
      remove(:name)
    end

    drop(constraint(:custom_lists_versions, "custom_lists_versions_version_source_id_fkey"))

    alter table(:custom_lists_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:custom_lists))

    drop(table(:custom_lists_versions))
  end
end
