defmodule Intellispark.Repo.Migrations.AddNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notes_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:notes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:notes_versions) do
      modify(
        :version_source_id,
        references(:notes,
          column: :id,
          name: "notes_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:notes) do
      add(:body, :text, null: false)
      add(:sensitive?, :boolean, null: false, default: false)
      add(:pinned?, :boolean, null: false, default: false)
      add(:pinned_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "notes_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "notes_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :author_id,
        references(:users,
          column: :id,
          name: "notes_author_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:notes, "notes_school_id_fkey"))

    drop(constraint(:notes, "notes_student_id_fkey"))

    drop(constraint(:notes, "notes_author_id_fkey"))

    alter table(:notes) do
      remove(:author_id)
      remove(:student_id)
      remove(:school_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:pinned_at)
      remove(:pinned?)
      remove(:sensitive?)
      remove(:body)
    end

    drop(constraint(:notes_versions, "notes_versions_version_source_id_fkey"))

    alter table(:notes_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:notes))

    drop(table(:notes_versions))
  end
end
