defmodule Intellispark.Repo.Migrations.AddFlagComments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:flag_comments_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:flag_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:flag_comments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:flag_comments_versions) do
      modify(
        :version_source_id,
        references(:flag_comments,
          column: :id,
          name: "flag_comments_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:flag_comments) do
      add(:body, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "flag_comments_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :flag_id,
        references(:flags,
          column: :id,
          name: "flag_comments_flag_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :author_id,
        references(:users,
          column: :id,
          name: "flag_comments_author_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:archived_at, :utc_datetime_usec)
    end
  end

  def down do
    drop(constraint(:flag_comments, "flag_comments_school_id_fkey"))

    drop(constraint(:flag_comments, "flag_comments_flag_id_fkey"))

    drop(constraint(:flag_comments, "flag_comments_author_id_fkey"))

    alter table(:flag_comments) do
      remove(:archived_at)
      remove(:author_id)
      remove(:flag_id)
      remove(:school_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:body)
    end

    drop(constraint(:flag_comments_versions, "flag_comments_versions_version_source_id_fkey"))

    alter table(:flag_comments_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:flag_comments))

    drop(table(:flag_comments_versions))
  end
end
