defmodule Intellispark.Repo.Migrations.AddStudentIdToTagStatusVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Nullable on purpose: paper-trail rows created before this migration
    # have no student_id to backfill with. New rows will populate it via
    # attributes_as_attributes on the source resource.
    alter table(:student_tags_versions) do
      add(:student_id, :uuid, null: true)
    end

    alter table(:student_statuses_versions) do
      add(:student_id, :uuid, null: true)
    end
  end

  def down do
    alter table(:student_statuses_versions) do
      remove(:student_id)
    end

    alter table(:student_tags_versions) do
      remove(:student_id)
    end
  end
end
