defmodule Intellispark.Repo.Migrations.AddHighFives do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:high_fives, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:body, :text, null: false)
      add(:recipient_email, :text, null: false)
      add(:token, :text, null: false)

      add(:sent_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:first_viewed_at, :utc_datetime_usec)
      add(:view_count, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "high_fives_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "high_fives_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :sent_by_id,
        references(:users,
          column: :id,
          name: "high_fives_sent_by_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :template_id,
        references(:high_five_templates,
          column: :id,
          name: "high_fives_template_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:high_fives, [:school_id, :token], name: "high_fives_unique_token_index")

    create table(:high_fives_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)

      add(
        :version_source_id,
        references(:high_fives,
          column: :id,
          name: "high_fives_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(constraint(:high_fives_versions, "high_fives_versions_version_source_id_fkey"))

    drop(table(:high_fives_versions))

    drop(constraint(:high_fives, "high_fives_school_id_fkey"))

    drop(constraint(:high_fives, "high_fives_student_id_fkey"))

    drop(constraint(:high_fives, "high_fives_sent_by_id_fkey"))

    drop(constraint(:high_fives, "high_fives_template_id_fkey"))

    drop_if_exists(
      unique_index(:high_fives, [:school_id, :token], name: "high_fives_unique_token_index")
    )

    drop(table(:high_fives))
  end
end
