defmodule Intellispark.Repo.Migrations.AddIndicatorScores do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:indicator_scores_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:dimension, :text, null: false)
      add(:level, :text, null: false)
      add(:school_id, :uuid, null: false)
      add(:student_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:indicator_scores, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:indicator_scores_versions) do
      modify(
        :version_source_id,
        references(:indicator_scores,
          column: :id,
          name: "indicator_scores_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:indicator_scores) do
      add(:dimension, :text, null: false)
      add(:level, :text, null: false)
      add(:score_value, :float, null: false)
      add(:answered_count, :bigint, null: false, default: 0)

      add(:last_computed_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)

      add(
        :school_id,
        references(:schools,
          column: :id,
          name: "indicator_scores_school_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :student_id,
        references(:students,
          column: :id,
          name: "indicator_scores_student_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :source_survey_assignment_id,
        references(:survey_assignments,
          column: :id,
          name: "indicator_scores_source_survey_assignment_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:indicator_scores, [:school_id, :student_id, :dimension],
             name: "indicator_scores_unique_per_student_dimension_index"
           )
  end

  def down do
    drop(constraint(:indicator_scores, "indicator_scores_school_id_fkey"))

    drop(constraint(:indicator_scores, "indicator_scores_student_id_fkey"))

    drop(constraint(:indicator_scores, "indicator_scores_source_survey_assignment_id_fkey"))

    drop_if_exists(
      unique_index(:indicator_scores, [:school_id, :student_id, :dimension],
        name: "indicator_scores_unique_per_student_dimension_index"
      )
    )

    alter table(:indicator_scores) do
      remove(:source_survey_assignment_id)
      remove(:student_id)
      remove(:school_id)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:last_computed_at)
      remove(:answered_count)
      remove(:score_value)
      remove(:level)
      remove(:dimension)
    end

    drop(
      constraint(:indicator_scores_versions, "indicator_scores_versions_version_source_id_fkey")
    )

    alter table(:indicator_scores_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:indicator_scores))

    drop(table(:indicator_scores_versions))
  end
end
